name: CD

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Déploiement
        run: |
          # Commandes de déploiement à exécuter ici

      
      - name: Génération des notes de release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Notes de la release pour la version ${{ github.ref_name }}.
            - Liste des modifications
            - Nouveautés
          draft: false
          prerelease: false
